### PR TITLE
refreshing the logged out state of the home page

### PR DESCRIPTION
**Pull request by JaymeeH**
Screenshot 2024-12-16 at 10 42 06 AM

### CODE REVIEW

**Comment by JaymeeH** [comment]
Hey @beth-german, im having trouble getting the css of the image to look as depicted in the figma example and wanted to get an extra pair of eyes before opening the pr. Would you mind taking a look at the current configuration and let me know which version of the figma mock-up we should be striving towards

**Comment by beth-german** [comment]
Hi Jaymee, Matt chose landing-6, I've marked it was ready for dev. https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=2045-17449&m=dev 

 
Frame 538

**Comment by kelynch** [comment]
Screenshots:
Screenshot 2024-12-16 at 3 34 59 PM
Screenshot 2024-12-16 at 3 35 18 PM

I think we may want to iterate on this to make the responsive experience better later on; I'll follow up with AUX colleagues on that in a separate ticket.

**Review by carolyncole — APPROVED** [review]
Thanks @JaymeeH and @kelynch

**Pull request merged**
